### ISSUE TITLE
Вывод тега [Radio] в перевод

### ISSUE THREAD

**Issue by kilroy98** [CrazyHackGUT/Radio#3]
@CrazyHackGUT, может кстати стоит вывести тег [Radio] в файл перевода? (https://github.com/CrazyHackGUT/Radio/blob/9b983c5a4f28f48c4b1704a423de9a9108866272/game/scripting/Radio/Timers.sp#L7#L9) 
Чтобы всё через перевод раскрашивать (если ты именно такой способ будешь делать).

**Comment by CrazyHackGUT** [comment]
Вынесу.

**Comment by CrazyHackGUT** [comment]
https://github.com/CrazyHackGUT/Radio/commit/25487d8a5f73cada3b94e658110ee2faa02b99d8
